### ISSUE TITLE
Bluebird PromisifyAll throws error

### ISSUE THREAD

**Issue by Nosherwan** [hokaccha/node-jwt-simple#12]
Hi,
I was trying to promisify jwt-simple api by using bluebirds Promise.promisifyAll method. It does promisify it but at runtime bluebird throws an error as follows:

Possibly unhandled Error: Algorithm not supported
    at Object.jwt_encode [as encode] (/Users/nosh/repos/dineawayserver/node_modules/jwt-simple/lib/jwt.js:114:11)
    at Object.encodeAsync (eval at makeNodePromisifiedEval (/Users/nosh/repos/dineawayserver/node_modules/sequelize/node_modules/bluebird/js/main/promisify.js:201:12), <anonymous>:12:22)
From previous event:
    at Object.encodeAsync (eval at makeNodePromisifiedEval (/Users/nosh/repos/dineawayserver/node_modules/sequelize/node_modules/bluebird/js/main/promisify.js:201:12), <anonymous>:7:21)

could this be that the library does not support async? or am I doing something wrong.

**Comment by petkaantonov** [comment]
The API is not async at all, there is no reason to promisify it. You can just call it:

```js
var jwt = require('jwt-simple');
var resuilt = jwt.encode(payload, secret);
console.log(result);
```

**Comment by hokaccha** [comment]
@petkaantonov That's right. :+1:
