### ISSUE TITLE
decode tokens crash when token is invalid

### ISSUE THREAD

**Issue by ray0324** [hokaccha/node-jwt-simple#91]
When try to decode a invalid token  it that doesn't match jwt format, it crashed  
such as  
```
jwt.decode('abcde');

```

**Comment by alexjab** [comment]
Hi @ray0324 

If you pass an invalid token, `decode` throws an error (it doesn't crash):

```
/Users/alex/Sources/tests/node_modules/jwt-simple/lib/jwt.js:66
 throw new Error('Not enough or too many segments');
    ^

Error: Not enough or too many segments
    at Object.jwt_decode [as decode] (/Users/alex/Sources/tests/node_modules/jwt-simple/lib/jwt.js:66:11)
    at Object.<anonymous> (/Users/alex/Sources/tests/index.jsx:3:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

You need to use `try...catch` if you want to properly handle that case.
